guardian/actions-merge-release-changes-to-protected-branch

- dist/index.js
- src/index.ts
This PR updates the logic on push events to use the return code of `git diff --quiet` to determine whether there are any changes. It also adds the `ignoreReturnCode` option when calling the command so that the process doesn't quit if there are changes.
Merge something into main on a repo which uses this action and see it run.
The process doesn't exit if a diff is detected.
> Handle diff exit code

- script/build
This PR adds a check in the `./script/build` file that runs in the CI environment which checks if there are any diffs after the build has fun. This means that the status checks will fail if the new build has not been commited. 
Try updating the action but not running the build and see the CI checks fail
It isn't possible to merge code that doesn't have an up-to-date build.
> Add CI check that build is up to date

- README.md
- action.yml
- dist/index.js
- src/config.ts
- src/index.ts
This PR refactors the config into a new file which exports an interface and a `getConfig` function. This function gets a number of user inputs and merges with the default config to produce the full config object. The `action.yml` file and  `README.md` are updated to detail the new inputs.
Configure the action using inputs and see the resultant output.
Options can be configured giving users more flexibility.
> Add inputs for some config items

- README.md
- action.yml
- dist/index.js
- src/config.ts
The following config values are set depending on the `package-manager` input provided (which defaults to npm). 
- maxFilesChanged
- maxFileChanges
- allowedFiles
- expectedChanges
Run the release process with `npm` and `yarn` and ensure it works as expected
Checks are tailored to the package manager in use
> Get config depending on package manager

- README.md
- action.yml
- dist/index.js
- src/index.ts
This PR adds a space between the `pullRequestPrefix` and `newVersion` when constructing the commit message and PR title. This space is required as otherwise the PR title validation fails. As the `pullRequestPrefix` value can be provided via an input and GitHub trims input strings, this space must be coded into the application rather than relying on the `pullRequestPrefix` value to provide the trailing space. A note has been added to the `README` and `action.yml` file to warn the users of this behaviour.
Run the release process and see that it works as expected
The automated release process works E2E.
> Add space between PR prefix and value

- README.md
- action.yml
- dist/index.js
- package-lock.json
- package.json
- src/index.ts
This PR updates the name of the action within the repository files. The new name has been proposed for two reason
1) Having a consistent `actions-` prefix across any custom actions we develop will make it easier to identify them
2) Giving the action a clear name makes its purpose immediately obvious to users and those reading workflow files in which it is implemented
**Note: Once approved the repository itself will be updated and any projects using it will also need to be updated**
The name of the action makes it immediately obvious what it does.
> chore: rename action

- dist/index.js
- src/index.ts
This change adds a new function which determines the merge method to use based on those allowed by the repository. It will use the first method allowed in order of `merge`, `squash`, `rebase`. If no methods are allowed (which shouldn't ever be the case as GitHub doesn't allow it) then we return `merge` by default.
Merge a PR which triggers a release to a repository that does not allow the `merge` method. See that it is merged using one of the alternative allowed methods.
Version bump PRs are still merged on repositories that don't allow the `merge` method.
> Use allowed merge method

- README.md
This PR adds a new section to the README which details the setup of semantic release using our recommended configuration. It also adds a contents section to the top of the file to make navigating the README easier.
Users of this action also have recommendations on how to set up the release itself.
> Add Configuring Releases section to README

- dist/index.js
- src/index.ts
This PR updates the logic used to add any changes to cater for the fact that different files change depending on the package manager used by the target repository. Instead of hardcoding the addition of the `package.json` and `package-lock.json`, we look through the `config.allowedFiles` array and add those files.
Try out the action on a repository that uses `yarn` and see that it still works as expected.
This action works for repositories using both `yarn` and `npm`
> fix: only add expected file changes

- dist/index.js
- src/config.ts
- src/index.ts
This PR updates the package manager specific configuration for `yarn` and fixes an incorrect error message.
Run a release on a repository that uses `yarn` as its package manager and see that the process completes as expected.
Releases run for repositories that use `yarn` too.
> Fix yarn config

- README.md
This PR adds a section to the README detailing the assumptions made about the merge-ability of a PR following automatic approval. 
Users are clear on the behaviour of the action
> Add a paragraph detailing the assumptions made when merging

- README.md
- action.yml
- dist/index.js
- src/config.ts
- src/index.ts
- src/utils.ts
This PR adds a new `additional-changes` input to the action which can be used to provide any extra changes which should be expected in a version bump PR. In order to accommodate this, some refactoring has been carried out on the package manager configuration. Documentation of how changes are verified has been added to the README.
On a repository that implements the action, open a PR that makes an extra change as well as the version bump changes. See that the action fails. Update the workflow configuration to permit the additional change an re-run the checks. See them pass.
The action can be configured to expect additional changes, making it more flexible.
> Add additional changes option

- README.md
This PR removes the warning from the top of the README that states this project is a WIP ahead of an impending v1 release.
> Remove WIP warning from README

- dist/index.js
- src/actions/raise-pull-request.ts
Currently, we get the new version number by `cat`ing the `package.json` and then parsing the output. This results in the `package.json` being written to the logs which adds clutter. This PR uses `fs` to read the file instead.
Merge a commit to the main branch in a repo that uses this action and see it in action.
Less cluttered logs
> Use fs to get new version number

- package-lock.json
- package.json
* Bumps [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest) from 26.0.21 to 26.0.22.
* Bumps [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin) from 4.19.0 to 4.20.0.
* Bumps [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser) from 4.19.0 to 4.20.0.
* Bumps [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) from 24.3.2 to 24.3.4.
> chore(deps): dependabot 06/04/21

- dist/index.js
- dist/licenses.txt
- package-lock.json
- package.json
- src/actions/merge-pull-request.ts
- src/actions/raise-pull-request.ts
- src/actions/should-merge-pull-request.test.ts
- src/actions/should-merge-pull-request.ts
- src/actions/validate-pull-request.test.ts
- src/actions/validate-pull-request.ts
- src/index.ts
Bump the `@actions` libs:
* chore(deps): bump @actions/github from 4.0.0 to 5.0.0
* chore(deps): bump @actions/core from 1.2.7 to 1.3.0
Add `.rest` everywhere we use `octokit`
> Bump actions libs and fix breaking changes

- package-lock.json
- package.json
* bump @typescript-eslint/parser from 4.26.1 to 4.28.0
* bump @guardian/eslint-config from 0.5.0 to 0.6.0
* bump @typescript-eslint/eslint-plugin from 4.27.0 to 4.28.0
* bump @guardian/eslint-config-typescript from 0.5.0 to 0.6.0
> chore: deps (28/06)

- .npmrc
- package.json
This PR adds some configuration so that running `yarn` commands will fail. This prevents accidental usage of `yarn` (instead of `npm`) and therefore erroneous, inconsistent behaviour as the repository is configured to use `npm`.
Try running `yarn` and see that an error message is displayed. Try running `npm i` and see that it completes successfully.
No unexpected behaviour due to `yarn` being used by accident.
> Add engines config to prevent yarn use

- dist/index.js
- package-lock.json
- package.json
* bump eslint from 7.29.0 to 7.31.0
* bump @types/node from 16.3.1 to 16.3.3
* bump @octokit/types from 6.16.4 to 6.19.0
* bump @vercel/ncc from 0.28.6 to 0.29.0
* bump @actions/core from 1.3.0 to 1.4.0
> Chore: Bump dependencies (19/07)

- package-lock.json
- package.json
* bump @octokit/webhooks-types from 4.1.0 to 4.2.1
* bump @types/node from 16.3.3 to 16.4.3
* bump @octokit/types from 6.19.0 to 6.21.1
> chore: Bump dependencies (27/07)

- package-lock.json
- package.json
* bump @octokit/types from 6.21.1 to 6.22.0
* bump @types/node from 16.4.3 to 16.4.10
* bump type-fest from 1.2.2 to 1.3.0
* bump eslint from 7.31.0 to 7.32.0
* bump @octokit/webhooks-types from 4.2.1 to 4.2.2
> chore(deps): Bump dependencies (02/08)

- package-lock.json
- package.json
* bump @octokit/types from 6.25.0 to 6.27.0
* bump type-fest from 2.0.0 to 2.2.0
* bump husky from 7.0.1 to 7.0.2
* bump @types/node from 16.7.6 to 16.7.10
* bump typescript from 4.3.5 to 4.4.2
> chore(deps): Bump dependencies (06/09)

- .github/workflows/ci.yaml
- README.md
This change updates the _ci_ workflow to use caching implemented by [guardian/actions-setup-node](https://github.com/guardian/actions-setup-node) now that it's available. It also swaps out [bahmutov/npm-install](https://github.com/bahmutov/npm-install) for `npm ci` as we no longer need the caching implemented by that action.
> Use built in caching from setup-node action
